version: '3'
services:
  demo1:
    image: praqma/network-multitool
    container_name: demo1
    restart: always
    networks:
      - demonetwork
  demo2:
    image: praqma/network-multitool
    container_name: demo2
    restart: always
    networks:
      - demonetwork

networks:
  demonetwork:
    driver: bridge
